SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) TOTAL_SALES
FROM 
    (
        SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, 
            (TOTAL_SALES * PRICE) AS TOTAL_SALES
        FROM BOOK
        JOIN AUTHOR
            ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
        JOIN 
            (
                SELECT SUM(SALES) AS TOTAL_SALES, BOOK_ID
                FROM BOOK_SALES
                WHERE YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 01
                GROUP BY BOOK_ID    
            ) t
            ON t.BOOK_ID = BOOK.BOOK_ID
    ) t
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC