SELECT car.CAR_ID, car.CAR_TYPE, FLOOR((DAILY_FEE * 30) *(100 - DISCOUNT_RATE) / 100) AS FEE

FROM CAR_RENTAL_COMPANY_CAR car
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN plan
    ON car.CAR_TYPE = plan.CAR_TYPE
    AND plan.DURATION_TYPE = '30일 이상'


WHERE NOT EXISTS 
(
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY rental
    WHERE car.CAR_ID = rental.CAR_ID
        AND START_DATE <= '2022-11-30'
        AND END_DATE >= '2022-11-01' 
)

# FEE는 SELECT에서 만든 별칭이라서 WHERE에서 못 씀
# HAVING과 ORDER BY에서는 별칭 사용 가능
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC