SELECT product.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT product
JOIN FOOD_ORDER o
    ON product.PRODUCT_ID = o.PRODUCT_ID
WHERE YEAR(IN_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 05
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID