SELECT DISTINCT rental.CAR_ID AS CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY rental
JOIN CAR_RENTAL_COMPANY_CAR car
ON car.CAR_ID = rental.CAR_ID
WHERE MONTH(rental.START_DATE) = '10' and car.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;