SELECT i.ID, FISH_NAME, i.LENGTH
FROM (
    SELECT ID, FISH_TYPE, LENGTH, MAX(LENGTH) MAXLENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    ) t
JOIN FISH_NAME_INFO n
    ON t.FISH_TYPE = n.FISH_TYPE
JOIN FISH_INFO i
    ON t.MAXLENGTH = i.LENGTH and t.FISH_TYPE = i.FISH_TYPE
ORDER BY ID