SELECT i.ID, FISH_NAME, i.LENGTH
FROM FISH_INFO i
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) MAXLENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    ) t
    ON t.MAXLENGTH = i.LENGTH 
    and t.FISH_TYPE = i.FISH_TYPE
JOIN FISH_NAME_INFO n
    ON t.FISH_TYPE = n.FISH_TYPE
ORDER BY ID